#!/bin/ksh

# released under Creative Commons Attribution-ShareAlike 3.0
# http://creativecommons.org/licenses/by-sa/3.0/
# v1.1
# 3. 4. 2012

if [ $# -ne 0 ]; then
	folder="$*"
	hits=$(locate -ic $folder)
	if [ "$hits" == "0" ]; then
		echo "Folder named \"$folder\" not found."
	elif [ "$hits" == "1" ]; then
		directory=$(locate -i $folder)
		if [[ -d "$directory" && `echo ${line##*/} | tr [:upper:] [:lower:]` = *`echo $folder | tr [:upper:] [:lower:]`* ]]; then
			open $directory
		else
			echo "Folder named \"$folder\" not found."
		fi
	else
		c=0
		locate -i "$folder" | while read line
			do
				if [[ -d "$line" && `echo ${line##*/} | tr [:upper:] [:lower:]` = *`echo $folder | tr [:upper:] [:lower:]`* ]]; then
					result[c]="$line"
					((c++))
				fi
			done
		if (( c == 1 )); then
			open "${result[0]}"
		else
			for i in ${!result[*]}
				do
  	 			 	printf "%s\n" "${result[$i]}"
				done		
		fi
	fi
else
	echo "Usage: fo <folder name>"
fi
exit